server : 
   port : 8070
spring :
    h2:
     console:
       path: /h2
       enabled: true
       settings:
         web-allow-others: true     
    application :
       name : restaurant-service
       
    jpa:
      hibernate:
        ddl-auto: update
      generate-ddl: true
    
eureka:
  client:
     service-url:
        defaultzone: http://localhost:8761/eureka
        register-with-eureka: true    